### ISSUE TITLE
Android: If you hold your device in portrait mode and change border color in scanline, the effect overflows way past the screen

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#151]
As in, not only top half of the window (where TIC's screen is in portrait mode) is affected, but entire screen.

Portrait mode is basically needed for development since on-screen keyboard covers half of the screen in landscape mode.

**Comment by trelemar** [comment]
That's because TIC's display fits into the screen. The entire screen is usable space if you'd like. You can see that there isn't a cut-off by ```poke(0x3FF9+1,48)```. The whole screen is usable space.

**Comment by trelemar** [comment]
http://imgur.com/a/tyK5m

**Comment by darkhog** [comment]
In landscape mode, yes. In portrait mode... http://i.imgur.com/6r8RdVm.png

And you've pasted the exact issue yourself. Now tell me something. If it was "usable spaCE" as you call it, you surely could draw on it with ordinary TIC drawing functions such as SPR or pix, right? Try that and tell me how it went.

**Comment by trelemar** [comment]
Your very rude. I can't help you I'm sorry.

**Comment by darkhog** [comment]
First of all, it's "you're" and second, you're right. You can't help me. Only nesbox can since he's a dev of this wonderful fantasy computer.

**Comment by trelemar** [comment]
If it's in your mindset to make enemies with fellow TIC-80 users the first day you start using it, be my guest. No one will ever appreciate your little games you make if you act that way. Correcting my grammar for the sake of feeling superior is another fantastic personality trait. I'll be sure to proof read and submit my posts to my personal editor before you can read them from now on. Should I go back and edit my mistakes for you?

When I replied to you at the start of this issue I was genuinely trying to help you. I thought I could help because when I first started using TIC-80 it was 100% on my Android tablet. Since then I've been using my laptop. Certain things don't really port over well when using a touch screen.

If you weren't aware, I have collaborator rights here for helping nesbox with issues. You know why I have those rights? Because I like helping people discover this fantasy console. It's such a great platform that is somewhat overlooked because of it's similarities to PICO-8. So if someone doesn't fully understand why it does something, or needs help figuring something out, I'll contribute my thoughts and experiences with TIC-80 to try to help. You have no right to talk to me the way you did, and no one will help you if you continue to. TIC-80's community is small enough as it is.
