### ISSUE TITLE
Automatically initialize table when trying to index it

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#162]
I know this would break Lua a bit, but imagine all the characters we could save if we wouldn't have to call `somearray={}` before we access it for the first time.

In short, I propose changing Lua interpreter a bit so instead of throwing `attempt to index a nil value` error it would silently initialize the table when it's first indexed (unless it's already a "normal" variable).

**Comment by Crutiatix** [comment]
There are a lot of possibilities how to reduce size of code by changing a lua interpreter. But then It could not be called Lua no longer. TIC is about learning a programming and these little modifications in language will make it hard for those who already know Lua or for those who will want to use Lua in other projects than TIC. Modifing a Lua language in TIC could have negative impact on popularity of this fantasy console compared to others because of the need to learn and remember these differences in the language. I know you suggest only one little change but if one change will be made then it will not remain only with this one.
There are a lot of others possibilities how to reduce size of code and still preserve the Lua language standard.

**Comment by darkhog** [comment]
Well, Pico-8's lua diverges in places pretty wildly form "regular" lua and any programmer worth his/her salt would be able to get the differences once he/she moves to other Lua environments. Additionally, as long as what the differences are is well documented, I don't see a problem.

Keep in mind that Lua wasn't created with limits of fantasy consoles such as Pico-8 or TIC-80 in mind so some sacrifices have to be made.

**Comment by Crutiatix** [comment]
Not all what is in Pico-8 is the best. Because of TIC is inspired by Pico, It haven't to be its copy. TIC has its own path.

If I should choose between studying a documentation of modified version of lua and then standard lua which I can use immidiately in an others applications so I choose second option.

Keep in mind that TIC isn't intended just for advanced programmers but also for beginners.

My opinion is that If some language modifications should be made, only in a way that does not affect the standard. One option is to implement macros which will allow to optionally change syntax of lua but don't mess up the lua standard if none would be defined. But It would be big deal to implement it to TIC.

**Comment by nesbox** [comment]
I'm negative about any LUA hacks and want to leave it clean, so, beginners can use any Lua documentation found on the Internet to learn how to program. Also, I want to be able to update LUA lib at any time without patching a new version.
I think we can close the issue
