### ISSUE TITLE
Record option for the music editor

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#167]
Not necessarily MIDI record, frankly I think it'd be an overkill, but recording of the keyboard input as notes. The reason I'm asking is that I often find myself just "jamming" using my keyboard (regular, typing kind) in the SFX editor and coming up with better tunes that I can by carefully entering notes.

**Comment by hseiken** [comment]
I'd like to +1 this.  I'm a computer musician since trackers were the only thing you COULD use on computer to make music and using the computer keyboard as a musical device is indispensable for musicians to hack together expressive tunes naturally.  Even if the quantize/lag is boogered, it's still  better than no option at all.  

In short, +1 but don't spend too much time making it 'perfect', it just needs to be a basic option.  Maybe after 1.0, the music system can be tweaked or improved if live sequencing is a big thing for the sound designers.

**Comment by nesbox** [comment]
it's like _Follow Mode_ in Famitracker, will do...

**Comment by darkhog** [comment]
@hseiken Agreed. And any misrecorded thing (due to lag) can be then manually adjusted.

**Comment by nesbox** [comment]
Added _Record Music_ button

![record](https://user-images.githubusercontent.com/1101448/26893828-3bd990ec-4bc5-11e7-9cd0-e62b3b033aa3.gif)

done in .27

**Comment by guysoft** [comment]
Hey @nesbox The record button does not seem to exist on the later versions today, was it dropped? Is there some possibility to get it back?

**Comment by lustfeind** [comment]
Interessting.. why was it removed?
