### ISSUE TITLE
Camera function 

### ISSUE THREAD

**Issue by to90zeroblue** [nesbox/tic.computer#254]
The Pico8 camera function would be a nice feature to have. Also, an improvement would be to have smooth scrolling as an option. The pico8 camera gets jittery when it's slow. I know real consoles can't do this, but it would look really nice.

**Comment by ChildishGiant** [comment]
It'd be jittery since It can only move one pixel at a time. There are no half pixels in tic

**Comment by darkhog** [comment]
Not necessarily. All subpixel scrolling or movement ("half pixels" as you put it) does is store position in a floating point number then round it to the closest integer. With a bit of thought, it could be implemented in any language that has floating point numbers of any kind (or even in some cases with fixed-point arithmetic as well).

And yes, I can see how such function would be useful. While as I've said, it is possible to roll your own function like that (and I will have to for my legend of zelda clone as I plan to have some areas with smooth scrolling), having it would be a nice addition since you won't be wasting characters for a basic function like this.

If I were nesbox I'd chalk it up to "cool to have, but not a necessity" though.

**Comment by trelemar** [comment]
I don't believe TIC needs a camera function, but this issue inspired me to write a camera tutorial, and dealing with efficient map drawing. You can read it here:

https://github.com/nesbox/tic.computer/wiki/Camera-tutorial

I hope that it helps you some. 

_Sent from my HONOR FRD-L04 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nesbox** [comment]
so, we can live without camera function
closing...
