### ISSUE TITLE
Add some buttons/change axis buttons

### ISSUE THREAD

**Issue by Raidez** [nesbox/tic.computer#42]
Sorry for my bad language, I'm french ! :)

# Change axis buttons
I requesting to change axis buttons (left,up,right,down).
I think, it's would be more user-friendly if btn(0) and btn(1) return a integer variable for axis pressed:
- btn(0) return -1 => left pressed
- btn(0) return 1 => right pressed
- btn(0) return 0 => left or right are unpressed

### more realistic
In fact, on a joypad [NES joypad reference](http://previewcf.turbosquid.com/Preview/2014/05/23__23_08_08/Preview_1.jpg29442307-e897-4537-a69a-de3ea948c9fdLarger.jpg), it's impossible to press left and right in same time.

But with the current buttons configuration, I can do this:
`if btn(2) and btn(3) then x=x+1 end`

### more useful for moving object in axis
With -1 to 1, we can moving object in TIC axis:
```
-- 'hello world' demo

function btnAxis(which)
	if which==0 then --x axis
		a=2
		b=3
	elseif which==1 then --y axis
		a=0
		b=1
	end
	
	if btn(a) and btn(b) then
		return 0
	elseif btn(a) then
		return -1
	elseif btn(b) then
		return 1
	else
		return 0
	end
end

t=0
x=104
y=24

function TIC()
	--[[ old dummy code :)
	
	if btn(0) then y=y-1 end
	if btn(1) then y=y+1 end
	if btn(2) then x=x-1 end
	if btn(3) then x=x+1 end
	--]]
	
	-- new super function
	x=x+btnAxis(0)
	y=y+btnAxis(1)
	
	cls(12)
	spr(1+(t%60)/30,x,y,-1,4)
	print("HELLO WORLD!",84,64)
	t=t+1
end
```

# Add some buttons
I thinking about add *select*, *start*, *L trigger*, *R trigger* buttons, but I think it's to much.
How about add just *start* button ?

**Comment by Raidez** [comment]
Others advantages of changing axis buttons:
I don't know how TIC manage RAM but instead use 4 variables for axis buttons, this will use just 2.

**Comment by harraps** [comment]
not gonna happend
nesbox already fixed that each gamepad use 8bits of memory (for a total of 16bits)
so you have either 2 six-button controller or 1 mouse pointer with 1 button
as explained here:
https://github.com/nesbox/tic.computer/issues/36

More variables doesn't mean it use more RAM:
On TIC the direction for one controller are stored on 4bits.
When we recover the values for each of the directions in LUA, they are stored in booleans.
A booleans is 8bits (only 1 of those 8bits is used).
If we concider the axis as numbers we get 2 double precision floating point numbers stored on 64bits each. So we get 128bits for axis against 32bits for booleans.

Also TIC like PICO-8 doesn't prevent you from pressing two opposed direction at the same time.
Not because it is a mistake but because it was intended that way.

Yet we could have two additional action button on each controller since we have only 6buttons for 8bits.

**Comment by Raidez** [comment]
It would be nice if I get full ram layout to more understand how memory was managed :).

For axis buttons, I will use my own function.
For add buttons, Nesbox will choose ...

**Comment by nesbox** [comment]
@harraps thanks for the explanation :)
there are two additional buttons (because we have 2 free bits) but they are not mapped to keyboard buttons

**Comment by nesbox** [comment]
@Raidez I'll share full memory spec when it will more less stable.
