### ISSUE TITLE
Moonscript support

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#8]
- If the first line of the script as the exact tag "--[moonscript]" then all the code is in moonscript,
- otherwise it is in LUA

**Comment by harraps** [comment]
Now that I think about it. maybe a toggle button in the text editor panel would be better.
Because otherwise, you would have to change the syntax highlighting based on what is read in the first line.
And maybe a reserved byte in the .tic files to selected the language used.
0000 0000 -> LUA
0000 0001 -> moonscript

**Comment by nesbox** [comment]
Don't think that changing of syntax highlighting based on first line is a problem and like the idea with [moonscript] tag. Also as I see Moonscript keywords are the same as in Lua.

**Comment by nesbox** [comment]
Added Moonscript support in 0.15.0
https://twitter.com/tic_computer/status/822081314601963520

**Comment by nesbox** [comment]
done.
